# Site settings
title: TheSave's Github Pages
email: saverio.giallorenzo@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thesave.github.io" # the base hostname & protocol for your site
github_username:  thesave

# Build settings
markdown: kramdown
